### PR TITLE
Speed factor

### PR DESCRIPTION
**Pull request by fdeloche**
Adds a speed factor to parameters. Enables reseting on launch.

### CODE REVIEW

**Comment by carsonip** [comment]
@fdeloche thanks for the PR. Sorry for the delay since I was afk for a while. I'll get back to you in a few days.

**Comment by carsonip** [comment]
@fdeloche The PR looks nice overall. Just 2 things:
1. I am still having trouble understanding the interval mod counter. Care to elaborate its use? Can you give an example when it will be useful?
2. Code formatting: can you use ClangFormat to format the code such that it looks consistent with the rest of the code? I will do it after merge if you don't.
Thanks!

**Comment by fdeloche** [comment]
@carsonip 
Hello,
1. Ok the problem is that currentTime, INTERVAL are int. INTERVAL is 200 ms, a slight modification would be to have a value of 199 or 201 instead, resulting in a precision of 0.5% for time shifting. There is no direct way to reach a better precision. It could seem to be faire enough, but actually on scale of minutes, this is a quite poor precision (shift of 1 second every three minutes). One way to get around this problem is to have float instead of int, or to have int that represent let's say microseconds. But then a big part of the code would have to be rewritten. Another way is to simulate finer time precision with varying values. For example a value of 199.5 ms for interval can be simulated by 199 - 200 - 199 - 200 ... That is exactly the purpose of interval mod counter. This way the finer shift for interval is of order 0.125% (around 1 second every ten minutes).
2. I don't know what is ClangFormat.

**Comment by carsonip** [comment]
Hi @fdeloche, I looked through the code again and I understand what you are doing now. I only have issues with the code inside the `update()` function.
1. Now it also does the simulation for normal users with 1.000 speed factor and actually making the `currentTime` ahead of what it should be (since the correction is always applied, rounded and added to `currentTime`).
2. Would it be better to actually sum the fractional part to a double/float variable and add the integral part of the variable to `currentTime` once it gets significant (e.g. >1)? A useful function would be `modf()`. Please let me know what you think about this.

**Comment by carsonip** [comment]
Hi @fdeloche, since this feature is requested by other users, we shouldn't keep them waiting for this. I will merge this PR and modify it in my own way if you don't modify the PR in a few days. Thank you very much again!

**Comment by fdeloche** [comment]
Hello @carsonip, sorry for the delay, was on holiday.
I'm not sure to get the problem there. The (int) conversion is not rounding but truncating in C++, so I think it already does what you say. If I print out the value of currentTimeIncr in normal behavior, I get a constant value of 200.

**Comment by carsonip** [comment]
@fdeloche, you're right, my bad. I'll merge this to `develop` branch and fix some styles. It is all good.

Also, I would like to ask again: If we are about precision, would it be better to actually sum the fractional part to a double/float variable and add the integral part of the variable to currentTime once it gets significant (e.g. >1)? Instead of simulating using integers.

**Comment by fdeloche** [comment]
@carsonip I understand now your second point. You're right it could be nicer.

**Pull request merged**
